// console.log(typeof('hello'));
// console.log(typeof(5));
// console.log(typeof({}));
// console.log(typeof(false));
// console.log(typeof(true));
// console.log(typeof(null));
// console.log(typeof(underfined));
// console.log(typeof(123n));
// console.log(typeof(String(5)));
let name = prompt ('String typedagi malumot kiriting')
let surname = +prompt ('Number typedagi malumot kiriting')
let age = prompt ('boolean typedagi malumot kiriting')
alert ('hamma malumotlarni togri kiritganzga ishoncingiz komilmi?')
alert(`siz kiritgan Mirsaid sozi ${typeof(name)} typega tegishli
siz kiritgan 123 sozi ${typeof(surname)} typega tegishli
siz kiritgan true sozi ${typeof(Boolean (age))} typega tegishli
`)
